pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Environment') {
            steps {
                // dir('project1') forces Jenkins to run these commands inside that subfolder
                dir('project1') {
                    python3 -m venv venv
                    ./venv/bin/pip install --upgrade pip
                    // Note: matching your file name 'requirement.txt'
                    ./venv/bin/pip install -r requirement.txt
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('project1') {
                    ./venv/bin/pytest
                }
            }
        }

        stage('Build & Package') {
            steps {
                dir('project1') {
                    sh 'tar --exclude="venv" --exclude="__pycache__" --exclude=".pytest_cache" -czf hello-devops.tar.gz .'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Directs Jenkins to find the tarball inside the project1 folder
                archiveArtifacts artifacts: 'project1/hello-devops.tar.gz', fingerprint: true
            }
        }
    }
}
