pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Environment') {
            steps {
                dir('project1') {
                    // Added 'sh' and wrapped the block in triple quotes
                    sh '''
                        python3 -m venv venv
                        ./venv/bin/pip install --upgrade pip
                        ./venv/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir('project1') {
                    sh './venv/bin/pytest'
                }
            }
        }

        stage('Build & Package') {
            steps {
                dir('project1') {
                    sh 'tar --exclude="venv" --exclude="__pycache__" --exclude=".pytest_cache" -czf hello-devops.tar.gz .'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'project1/hello-devops.tar.gz', fingerprint: true
            }
        }
    }
}
